apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-high-cpu
  namespace: monitoring
spec:
  groups:
    - name: node.rules
      rules:
        - alert: HighCPUUsage
          expr: 100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[5m]))) > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Node CPU usage is above 80% for 5 minutes."
