name: CI/CD Frontend

on:
  push:
    paths:
      - apps/frontend-app/**
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Kubeconfig
        run: |
            echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
            echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Deploy to Kubernetes
        run: kubectl apply -f ./deploy.yml --validate=false
        working-directory: ./apps/frontend-app

      



