name: CI/CD Frontend

on:
  push:
    
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Set up Kubeconfig
        run: |
            echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
            echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV
      - name: Deploy Frontend with kubectl
        run: kubectl apply -f deploy.yml
        working-directory: apps/frontend-app

      # - name: Deploy to Kubernetes
      #   working-directory: apps/frontend-app
      #   run: kubectl apply -f ./deploy.yml --validate=false
        

      



